export interface Guest {
  id: string;
  name: string;
  checkInTime: string;
  role: string; // Generated by Gemini
  welcomeMessage: string; // Generated by Gemini
  emoji: string; // Generated by Gemini
}

export type ViewState = 'landing' | 'check-in' | 'success' | 'list';

export interface GeminiBadgeResponse {
  role: string;
  welcomeMessage: string;
  emoji: string;
}
